// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Ride_In_Console

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SPLASH_SCR
void ui_SPLASH_SCR_screen_init(void);
void ui_event_SPLASH_SCR(lv_event_t * e);
lv_obj_t * ui_SPLASH_SCR;
lv_obj_t * ui_RIDE_IN_CONSOLE_IMG;
lv_obj_t * ui_RIDE_IN_CONSOLE_TXT;
lv_obj_t * ui_SUBTITULO_TXT;
lv_obj_t * ui_CARGANDO_SPN;
lv_obj_t * ui_CARGANDO_TXT;


// SCREEN: ui_CONSOLE_SCR
void ui_CONSOLE_SCR_screen_init(void);
lv_obj_t * ui_CONSOLE_SCR;
lv_obj_t * ui_UBICACION_IMG;
lv_obj_t * ui_UBICACION_TXT;
lv_obj_t * ui_CLIMA_IMG;
lv_obj_t * ui_CLIMA_TXT;
lv_obj_t * ui_VIENTO_IMG;
lv_obj_t * ui_VIENTO_TXT;
lv_obj_t * ui_BLUETOOTH_IMG;
lv_obj_t * ui_BLUETOOTH_TXT;
lv_obj_t * ui_GASOLINA_IMG;
lv_obj_t * ui_GASOLINE;
lv_obj_t * ui_GASOLINA_TXT;
lv_obj_t * ui_HORA_TXT;
lv_obj_t * ui_VELOCIMETRO;
lv_obj_t * ui_VELOCIDAD_TXT;
lv_obj_t * ui_KILOMETRAJE_TXT;
lv_obj_t * ui_RPMX1000;
lv_obj_t * ui_RPM_TXT;
lv_obj_t * ui_FOCOS_IMG;
lv_obj_t * ui_FOCOS_TXT;
lv_obj_t * ui_CAMBIOS_TXT;
lv_obj_t * ui_BATERIA_IMG;
lv_obj_t * ui_BATERIA_TXT;
lv_obj_t * ui_TEMPERATURA_MOTOR_IMG;
lv_obj_t * ui_TEMPERATURA_MOTOR_TXT;
lv_obj_t * ui_DIR_IZQ_IMG;
lv_obj_t * ui_DIR_DER_IMG;
lv_obj_t * ui_RIDE_IN_KICK_CNT;
lv_obj_t * ui_CONSEJO_TXT;
lv_obj_t * ui_DETALLE_MOTO_TXT;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_x[1] = {&ui_img_180x180_png};
const lv_img_dsc_t * ui_imgset_console_motor_[1] = {&ui_img_console_motor_000000_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SPLASH_SCR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_CONSOLE_SCR, LV_SCR_LOAD_ANIM_FADE_ON, 600, 1500, &ui_CONSOLE_SCR_screen_init);
        _ui_screen_delete(&ui_SPLASH_SCR);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SPLASH_SCR_screen_init();
    ui_CONSOLE_SCR_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SPLASH_SCR);
}
