// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Ride_In_Console

#ifndef _SQUARELINE_RIDE_IN_CONSOLE_UI_H
#define _SQUARELINE_RIDE_IN_CONSOLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_SPLASH_SCR
void ui_SPLASH_SCR_screen_init(void);
void ui_event_SPLASH_SCR(lv_event_t * e);
extern lv_obj_t * ui_SPLASH_SCR;
extern lv_obj_t * ui_RIDE_IN_CONSOLE_IMG;
extern lv_obj_t * ui_RIDE_IN_CONSOLE_TXT;
extern lv_obj_t * ui_SUBTITULO_TXT;
extern lv_obj_t * ui_CARGANDO_SPN;
extern lv_obj_t * ui_CARGANDO_TXT;
// SCREEN: ui_CONSOLE_SCR
void ui_CONSOLE_SCR_screen_init(void);
extern lv_obj_t * ui_CONSOLE_SCR;
extern lv_obj_t * ui_UBICACION_IMG;
extern lv_obj_t * ui_UBICACION_TXT;
extern lv_obj_t * ui_CLIMA_IMG;
extern lv_obj_t * ui_CLIMA_TXT;
extern lv_obj_t * ui_VIENTO_IMG;
extern lv_obj_t * ui_VIENTO_TXT;
extern lv_obj_t * ui_BLUETOOTH_IMG;
extern lv_obj_t * ui_BLUETOOTH_TXT;
extern lv_obj_t * ui_GASOLINA_IMG;
extern lv_obj_t * ui_GASOLINE;
extern lv_obj_t * ui_GASOLINA_TXT;
extern lv_obj_t * ui_HORA_TXT;
extern lv_obj_t * ui_VELOCIMETRO;
extern lv_obj_t * ui_VELOCIDAD_TXT;
extern lv_obj_t * ui_KILOMETRAJE_TXT;
extern lv_obj_t * ui_RPMX1000;
extern lv_obj_t * ui_RPM_TXT;
extern lv_obj_t * ui_FOCOS_IMG;
extern lv_obj_t * ui_FOCOS_TXT;
extern lv_obj_t * ui_CAMBIOS_TXT;
extern lv_obj_t * ui_BATERIA_IMG;
extern lv_obj_t * ui_BATERIA_TXT;
extern lv_obj_t * ui_TEMPERATURA_MOTOR_IMG;
extern lv_obj_t * ui_TEMPERATURA_MOTOR_TXT;
extern lv_obj_t * ui_DIR_IZQ_IMG;
extern lv_obj_t * ui_DIR_DER_IMG;
extern lv_obj_t * ui_RIDE_IN_KICK_CNT;
extern lv_obj_t * ui_CONSEJO_TXT;
extern lv_obj_t * ui_DETALLE_MOTO_TXT;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_ride_in_console_png);    // assets/logo_ride_in_console.png
LV_IMG_DECLARE(ui_img_fondo_ride_in_console_rex_150_rnb_png);    // assets/fondo_ride_in_console_rex_150_rnb.png
LV_IMG_DECLARE(ui_img_console_ubicacion_png);    // assets/console_ubicacion.png
LV_IMG_DECLARE(ui_img_clear_png);    // assets/Clear.png
LV_IMG_DECLARE(ui_img_console_wind_png);    // assets/console_wind.png
LV_IMG_DECLARE(ui_img_console_bluetooth_png);    // assets/console_bluetooth.png
LV_IMG_DECLARE(ui_img_618658798);    // assets/lata-de-gasolina.png
LV_IMG_DECLARE(ui_img_180x180_png);    // assets/180X180.png
LV_IMG_DECLARE(ui_img_1851428151);    // assets/luz-del-coche (3).png
LV_IMG_DECLARE(ui_img_console_battery_ffffff_png);    // assets/console_battery_FFFFFF.png
LV_IMG_DECLARE(ui_img_console_motor_000000_png);    // assets/console_motor_000000.png
LV_IMG_DECLARE(ui_img_773449086);    // assets/flecha-correcta (1).png
LV_IMG_DECLARE(ui_img_773443835);    // assets/flecha-correcta (2).png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/Cloudy.png
LV_IMG_DECLARE(ui_img_console_battery_png);    // assets/console_battery.png
LV_IMG_DECLARE(ui_img_console_motor_png);    // assets/console_motor.png
LV_IMG_DECLARE(ui_img_console_ride_in_kick_png);    // assets/console_ride_in_kick.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/Fog.png
LV_IMG_DECLARE(ui_img_heavy_rain_png);    // assets/Heavy rain.png
LV_IMG_DECLARE(ui_img_heavy_showers_png);    // assets/Heavy showers.png
LV_IMG_DECLARE(ui_img_heavy_snow_showers_png);    // assets/Heavy snow showers.png
LV_IMG_DECLARE(ui_img_heavy_snow_png);    // assets/Heavy snow.png
LV_IMG_DECLARE(ui_img_light_rain_png);    // assets/Light rain.png
LV_IMG_DECLARE(ui_img_light_showers_png);    // assets/Light showers.png
LV_IMG_DECLARE(ui_img_light_sleet_showers_png);    // assets/Light sleet showers.png
LV_IMG_DECLARE(ui_img_light_sleet_png);    // assets/Light sleet.png
LV_IMG_DECLARE(ui_img_light_snow_showers_png);    // assets/Light snow showers.png
LV_IMG_DECLARE(ui_img_light_snow_png);    // assets/Light snow.png
LV_IMG_DECLARE(ui_img_1851423024);    // assets/luz-del-coche (4).png
LV_IMG_DECLARE(ui_img_partly_cloudy_png);    // assets/Partly cloudy.png
LV_IMG_DECLARE(ui_img_snow_showers_png);    // assets/Snow showers.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets/Sunny.png
LV_IMG_DECLARE(ui_img_thundery_heavy_rain_png);    // assets/Thundery heavy rain.png
LV_IMG_DECLARE(ui_img_thundery_showers_png);    // assets/Thundery showers.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
