// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Ride_In_Console

#include "ui.h"

void ChangeStatsChart(lv_event_t * e)
{
	// Your code here
}

void ChangeTimeChart(lv_event_t * e)
{
	// Your code here
}
