// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Ride_In_Console

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ChangeStatsChart(lv_event_t * e);
void ChangeTimeChart(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
