// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Ride_In_Console

#include "ui.h"

void ui_SPLASH_SCR_screen_init(void)
{
    ui_SPLASH_SCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SPLASH_SCR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SPLASH_SCR, lv_color_hex(0x002346), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SPLASH_SCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RIDE_IN_CONSOLE_IMG = lv_img_create(ui_SPLASH_SCR);
    lv_img_set_src(ui_RIDE_IN_CONSOLE_IMG, &ui_img_logo_ride_in_console_png);
    lv_obj_set_width(ui_RIDE_IN_CONSOLE_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RIDE_IN_CONSOLE_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RIDE_IN_CONSOLE_IMG, 0);
    lv_obj_set_y(ui_RIDE_IN_CONSOLE_IMG, -120);
    lv_obj_set_align(ui_RIDE_IN_CONSOLE_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RIDE_IN_CONSOLE_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RIDE_IN_CONSOLE_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RIDE_IN_CONSOLE_TXT = lv_label_create(ui_SPLASH_SCR);
    lv_obj_set_width(ui_RIDE_IN_CONSOLE_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RIDE_IN_CONSOLE_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RIDE_IN_CONSOLE_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RIDE_IN_CONSOLE_TXT, "Ride In Console");
    lv_obj_set_style_text_color(ui_RIDE_IN_CONSOLE_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RIDE_IN_CONSOLE_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RIDE_IN_CONSOLE_TXT, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SUBTITULO_TXT = lv_label_create(ui_SPLASH_SCR);
    lv_obj_set_width(ui_SUBTITULO_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SUBTITULO_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SUBTITULO_TXT, 0);
    lv_obj_set_y(ui_SUBTITULO_TXT, 35);
    lv_obj_set_align(ui_SUBTITULO_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SUBTITULO_TXT, "del sistema Ride In");
    lv_obj_set_style_text_color(ui_SUBTITULO_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SUBTITULO_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SUBTITULO_TXT, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CARGANDO_SPN = lv_spinner_create(ui_SPLASH_SCR, 1000, 90);
    lv_obj_set_width(ui_CARGANDO_SPN, 50);
    lv_obj_set_height(ui_CARGANDO_SPN, 50);
    lv_obj_set_x(ui_CARGANDO_SPN, 0);
    lv_obj_set_y(ui_CARGANDO_SPN, 150);
    lv_obj_set_align(ui_CARGANDO_SPN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CARGANDO_SPN, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_CARGANDO_SPN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CARGANDO_SPN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CARGANDO_SPN, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CARGANDO_SPN, lv_color_hex(0xFFA500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CARGANDO_SPN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CARGANDO_SPN, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CARGANDO_TXT = lv_label_create(ui_SPLASH_SCR);
    lv_obj_set_width(ui_CARGANDO_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CARGANDO_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CARGANDO_TXT, 0);
    lv_obj_set_y(ui_CARGANDO_TXT, 200);
    lv_obj_set_align(ui_CARGANDO_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CARGANDO_TXT, "cargando...");
    lv_obj_set_style_text_color(ui_CARGANDO_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CARGANDO_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CARGANDO_TXT, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SPLASH_SCR, ui_event_SPLASH_SCR, LV_EVENT_ALL, NULL);

}
