// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Ride_In_Console

#include "ui.h"

void ui_CONSOLE_SCR_screen_init(void)
{
    ui_CONSOLE_SCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CONSOLE_SCR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CONSOLE_SCR, lv_color_hex(0x002346), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONSOLE_SCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CONSOLE_SCR, &ui_img_fondo_ride_in_console_rex_150_rnb_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UBICACION_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_UBICACION_IMG, &ui_img_console_ubicacion_png);
    lv_obj_set_width(ui_UBICACION_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UBICACION_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UBICACION_IMG, -378);
    lv_obj_set_y(ui_UBICACION_IMG, -225);
    lv_obj_set_align(ui_UBICACION_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UBICACION_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UBICACION_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UBICACION_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_UBICACION_TXT, 156);
    lv_obj_set_height(ui_UBICACION_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UBICACION_TXT, -288);
    lv_obj_set_y(ui_UBICACION_TXT, -225);
    lv_obj_set_align(ui_UBICACION_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UBICACION_TXT, "cargando...");
    lv_obj_set_style_text_color(ui_UBICACION_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UBICACION_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UBICACION_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UBICACION_TXT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CLIMA_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_CLIMA_IMG, &ui_img_clear_png);
    lv_obj_set_width(ui_CLIMA_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CLIMA_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CLIMA_IMG, -178);
    lv_obj_set_y(ui_CLIMA_IMG, -225);
    lv_obj_set_align(ui_CLIMA_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CLIMA_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CLIMA_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CLIMA_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_CLIMA_TXT, 156);
    lv_obj_set_height(ui_CLIMA_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CLIMA_TXT, -88);
    lv_obj_set_y(ui_CLIMA_TXT, -225);
    lv_obj_set_align(ui_CLIMA_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CLIMA_TXT, "cargando...");
    lv_obj_set_style_text_color(ui_CLIMA_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CLIMA_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CLIMA_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CLIMA_TXT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VIENTO_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_VIENTO_IMG, &ui_img_console_wind_png);
    lv_obj_set_width(ui_VIENTO_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VIENTO_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VIENTO_IMG, 22);
    lv_obj_set_y(ui_VIENTO_IMG, -225);
    lv_obj_set_align(ui_VIENTO_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VIENTO_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VIENTO_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VIENTO_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_VIENTO_TXT, 156);
    lv_obj_set_height(ui_VIENTO_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VIENTO_TXT, 112);
    lv_obj_set_y(ui_VIENTO_TXT, -225);
    lv_obj_set_align(ui_VIENTO_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VIENTO_TXT, "cargando...");
    lv_obj_set_style_text_color(ui_VIENTO_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VIENTO_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VIENTO_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VIENTO_TXT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_BLUETOOTH_IMG, &ui_img_console_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLUETOOTH_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLUETOOTH_IMG, 222);
    lv_obj_set_y(ui_BLUETOOTH_IMG, -225);
    lv_obj_set_align(ui_BLUETOOTH_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BLUETOOTH_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_BLUETOOTH_TXT, 156);
    lv_obj_set_height(ui_BLUETOOTH_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLUETOOTH_TXT, 312);
    lv_obj_set_y(ui_BLUETOOTH_TXT, -225);
    lv_obj_set_align(ui_BLUETOOTH_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLUETOOTH_TXT, "No conectado");
    lv_obj_set_style_text_color(ui_BLUETOOTH_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLUETOOTH_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BLUETOOTH_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLUETOOTH_TXT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GASOLINA_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_GASOLINA_IMG, &ui_img_618658798);
    lv_obj_set_width(ui_GASOLINA_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GASOLINA_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GASOLINA_IMG, -350);
    lv_obj_set_y(ui_GASOLINA_IMG, -170);
    lv_obj_set_align(ui_GASOLINA_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GASOLINA_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GASOLINA_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GASOLINE = lv_bar_create(ui_CONSOLE_SCR);
    lv_bar_set_value(ui_GASOLINE, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_GASOLINE, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_GASOLINE, 32);
    lv_obj_set_height(ui_GASOLINE, 210);
    lv_obj_set_x(ui_GASOLINE, -350);
    lv_obj_set_y(ui_GASOLINE, -33);
    lv_obj_set_align(ui_GASOLINE, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GASOLINE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GASOLINE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GASOLINE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GASOLINE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GASOLINE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GASOLINE, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GASOLINE, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GASOLINA_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_GASOLINA_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GASOLINA_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GASOLINA_TXT, -350);
    lv_obj_set_y(ui_GASOLINA_TXT, 104);
    lv_obj_set_align(ui_GASOLINA_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GASOLINA_TXT, "0%");
    lv_obj_set_style_text_color(ui_GASOLINA_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GASOLINA_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GASOLINA_TXT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HORA_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_HORA_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HORA_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HORA_TXT, -158);
    lv_obj_set_y(ui_HORA_TXT, -170);
    lv_obj_set_align(ui_HORA_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HORA_TXT, "04:20");
    lv_obj_set_style_text_color(ui_HORA_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HORA_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HORA_TXT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VELOCIMETRO = lv_arc_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_VELOCIMETRO, 256);
    lv_obj_set_height(ui_VELOCIMETRO, 256);
    lv_obj_set_x(ui_VELOCIMETRO, -158);
    lv_obj_set_y(ui_VELOCIMETRO, 0);
    lv_obj_set_align(ui_VELOCIMETRO, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_VELOCIMETRO, 0, 160);
    lv_arc_set_value(ui_VELOCIMETRO, 50);

    lv_obj_set_style_bg_color(ui_VELOCIMETRO, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VELOCIMETRO, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_VELOCIMETRO, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VELOCIMETRO, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VELOCIMETRO, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VELOCIMETRO, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_VELOCIMETRO, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_VELOCIMETRO, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_VELOCIMETRO, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_VELOCIMETRO, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VELOCIDAD_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_VELOCIDAD_TXT, 119);
    lv_obj_set_height(ui_VELOCIDAD_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VELOCIDAD_TXT, -158);
    lv_obj_set_y(ui_VELOCIDAD_TXT, -6);
    lv_obj_set_align(ui_VELOCIDAD_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VELOCIDAD_TXT, "");
    lv_obj_set_style_text_color(ui_VELOCIDAD_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VELOCIDAD_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VELOCIDAD_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VELOCIDAD_TXT, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KILOMETRAJE_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_KILOMETRAJE_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KILOMETRAJE_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KILOMETRAJE_TXT, -158);
    lv_obj_set_y(ui_KILOMETRAJE_TXT, 104);
    lv_obj_set_align(ui_KILOMETRAJE_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KILOMETRAJE_TXT, "14.000 KM");
    lv_obj_set_style_text_color(ui_KILOMETRAJE_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KILOMETRAJE_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_KILOMETRAJE_TXT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMX1000 = lv_arc_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_RPMX1000, 180);
    lv_obj_set_height(ui_RPMX1000, 180);
    lv_obj_set_x(ui_RPMX1000, 120);
    lv_obj_set_y(ui_RPMX1000, 30);
    lv_obj_set_align(ui_RPMX1000, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RPMX1000, 0, 12000);
    lv_arc_set_value(ui_RPMX1000, 1000);
    lv_obj_set_style_bg_img_src(ui_RPMX1000, &ui_img_180x180_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RPMX1000, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPMX1000, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RPMX1000, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPMX1000, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPMX1000, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMX1000, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_RPMX1000, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_RPMX1000, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_RPMX1000, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_RPMX1000, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RPM_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_RPM_TXT, 95);
    lv_obj_set_height(ui_RPM_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM_TXT, 120);
    lv_obj_set_y(ui_RPM_TXT, 99);
    lv_obj_set_align(ui_RPM_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM_TXT, "");
    lv_obj_set_style_text_color(ui_RPM_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RPM_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM_TXT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FOCOS_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_FOCOS_IMG, &ui_img_1851428151);
    lv_obj_set_width(ui_FOCOS_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FOCOS_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FOCOS_IMG, 208);
    lv_obj_set_y(ui_FOCOS_IMG, -120);
    lv_obj_set_align(ui_FOCOS_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FOCOS_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FOCOS_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FOCOS_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_FOCOS_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FOCOS_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FOCOS_TXT, 208);
    lv_obj_set_y(ui_FOCOS_TXT, -70);
    lv_obj_set_align(ui_FOCOS_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FOCOS_TXT, "OFF");
    lv_obj_set_style_text_color(ui_FOCOS_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FOCOS_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FOCOS_TXT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CAMBIOS_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_CAMBIOS_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CAMBIOS_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CAMBIOS_TXT, 330);
    lv_obj_set_y(ui_CAMBIOS_TXT, 100);
    lv_obj_set_align(ui_CAMBIOS_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CAMBIOS_TXT, "N");
    lv_obj_set_style_text_color(ui_CAMBIOS_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CAMBIOS_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CAMBIOS_TXT, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BATERIA_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_BATERIA_IMG, &ui_img_console_battery_ffffff_png);
    lv_obj_set_width(ui_BATERIA_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BATERIA_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BATERIA_IMG, 300);
    lv_obj_set_y(ui_BATERIA_IMG, -50);
    lv_obj_set_align(ui_BATERIA_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BATERIA_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BATERIA_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BATERIA_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_BATERIA_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BATERIA_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BATERIA_TXT, 300);
    lv_obj_set_y(ui_BATERIA_TXT, -15);
    lv_obj_set_align(ui_BATERIA_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BATERIA_TXT, "12.0V");
    lv_obj_set_style_text_color(ui_BATERIA_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BATERIA_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BATERIA_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BATERIA_TXT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMPERATURA_MOTOR_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_TEMPERATURA_MOTOR_IMG, &ui_img_console_motor_000000_png);
    lv_obj_set_width(ui_TEMPERATURA_MOTOR_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMPERATURA_MOTOR_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPERATURA_MOTOR_IMG, 329);
    lv_obj_set_y(ui_TEMPERATURA_MOTOR_IMG, -175);
    lv_obj_set_align(ui_TEMPERATURA_MOTOR_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TEMPERATURA_MOTOR_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TEMPERATURA_MOTOR_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TEMPERATURA_MOTOR_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_TEMPERATURA_MOTOR_TXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMPERATURA_MOTOR_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPERATURA_MOTOR_TXT, 332);
    lv_obj_set_y(ui_TEMPERATURA_MOTOR_TXT, -130);
    lv_obj_set_align(ui_TEMPERATURA_MOTOR_TXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMPERATURA_MOTOR_TXT, "800°");
    lv_obj_set_style_text_color(ui_TEMPERATURA_MOTOR_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TEMPERATURA_MOTOR_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TEMPERATURA_MOTOR_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TEMPERATURA_MOTOR_TXT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIR_IZQ_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_DIR_IZQ_IMG, &ui_img_773449086);
    lv_obj_set_width(ui_DIR_IZQ_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIR_IZQ_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIR_IZQ_IMG, 67);
    lv_obj_set_y(ui_DIR_IZQ_IMG, 165);
    lv_obj_set_align(ui_DIR_IZQ_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DIR_IZQ_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DIR_IZQ_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIR_DER_IMG = lv_img_create(ui_CONSOLE_SCR);
    lv_img_set_src(ui_DIR_DER_IMG, &ui_img_773443835);
    lv_obj_set_width(ui_DIR_DER_IMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIR_DER_IMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIR_DER_IMG, 174);
    lv_obj_set_y(ui_DIR_DER_IMG, 165);
    lv_obj_set_align(ui_DIR_DER_IMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DIR_DER_IMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DIR_DER_IMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RIDE_IN_KICK_CNT = lv_obj_create(ui_CONSOLE_SCR);
    lv_obj_remove_style_all(ui_RIDE_IN_KICK_CNT);
    lv_obj_set_width(ui_RIDE_IN_KICK_CNT, 390);
    lv_obj_set_height(ui_RIDE_IN_KICK_CNT, 85);
    lv_obj_set_x(ui_RIDE_IN_KICK_CNT, -185);
    lv_obj_set_y(ui_RIDE_IN_KICK_CNT, 176);
    lv_obj_set_align(ui_RIDE_IN_KICK_CNT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RIDE_IN_KICK_CNT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RIDE_IN_KICK_CNT, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RIDE_IN_KICK_CNT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RIDE_IN_KICK_CNT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CONSEJO_TXT = lv_label_create(ui_RIDE_IN_KICK_CNT);
    lv_obj_set_width(ui_CONSEJO_TXT, 350);
    lv_obj_set_height(ui_CONSEJO_TXT, 64);
    lv_obj_set_align(ui_CONSEJO_TXT, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_CONSEJO_TXT, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_CONSEJO_TXT, "\nListo para dar una vuelta?");
    lv_obj_set_style_text_color(ui_CONSEJO_TXT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CONSEJO_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CONSEJO_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CONSEJO_TXT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DETALLE_MOTO_TXT = lv_label_create(ui_CONSOLE_SCR);
    lv_obj_set_width(ui_DETALLE_MOTO_TXT, 370);
    lv_obj_set_height(ui_DETALLE_MOTO_TXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DETALLE_MOTO_TXT, 205);
    lv_obj_set_y(ui_DETALLE_MOTO_TXT, 215);
    lv_obj_set_align(ui_DETALLE_MOTO_TXT, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_DETALLE_MOTO_TXT, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_DETALLE_MOTO_TXT, "Euromot Rex 150");
    lv_obj_set_style_text_color(ui_DETALLE_MOTO_TXT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DETALLE_MOTO_TXT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DETALLE_MOTO_TXT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DETALLE_MOTO_TXT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
